### ISSUE TITLE
"Old Versions" directory is redundant

### ISSUE THREAD

**Issue by postolka** [samytichadou/CatHide#2]
Is there any reaso for "Old Versions" directory? GIT keeps track of old versions by itself, so there is no need to copy old vresion to some "Old Versions" directory. You can even use tags to mark certain version.

**Comment by samytichadou** [comment]
Ok, im new to github, didn t lnow that, so if i erase every old versions of the addon, it will keep them ? Even if i re upload every new version ? Thanls for the advice !

**Comment by postolka** [comment]
Yes, you can. Just click "## Commits" link in top part on "Code" tab. Then, you can see all your changes (commits). If you click "<>" button on any of commits, you can browse or even download your code at that point in history, but you should be able to access history even without browser or Internet connection on your computer via your GIT (or GitHub) client. Accessing history and reverting changes is one of core GIT features - you should take closer look to GIT to take full advantage.
Anyway, thanks for sharing and maintaining your plugin :D
