### ISSUE TITLE
Error when pressing refresh in Blender 2.83

### ISSUE THREAD

**Issue by giacometti777** [samytichadou/CatHide#6]
Unfortunately I get this error in Blender 2.83:

Error: Traceback (most recent call last):
File “C:\Users*\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\CatHide-2_8\operator\refresh_lists_operator.py", line 70, in execute
createPanelCategoriesProperties()
File "C:\Users*\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\CatHide-2_8\functions\panel_functions.py”, line 43, in createPanelCategoriesProperties
panels, categories, child_panels = getAllPanelFromSpaceRegion(“VIEW_3D”, “UI”)
File “C:\Users****\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\CatHide-2_8\functions\panel_functions.py”, line 29, in getAllPanelFromSpaceRegion
if panel.bl_category not in category_list:
AttributeError: type object ‘BAKETOOL_PT_UV’ has no attribute ‘bl_category’

location: :-1

**Comment by samytichadou** [comment]
Thanks for the report, will take a look asap !

**Comment by samytichadou** [comment]
possible fix in https://github.com/samytichadou/CatHide/commit/9739c1f582dcabb40f365fddea00c5cd8fc972c5
